services:

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring
    restart: unless-stopped

networks:
  spring:
    driver: bridge
